import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { MainStoreProvider } from "@src/stores/mainStoreProvider";
import ReactQueryProviders from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "aptner-pass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProviders>
          <MainStoreProvider>
            <header>
              <h1>GitHub 유저 검색 및 북마크</h1>
              <nav>
                <ul>
                  <li>
                    <Link href="/all-users">모든 유저</Link>
                  </li>
                  <li>
                    <Link href="/bookmarked">북마크된 유저</Link>
                  </li>
                </ul>
              </nav>
            </header>
            <main>{children}</main>
          </MainStoreProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
