import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { MainStoreProvider } from "@src/stores/mainStoreProvider";
import ReactQueryProviders from "./providers";
import FloatingActionButton from "@src/components/FloatingActionButton/FloatingActionButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "aptner-pass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr" style={{ scrollbarGutter: "stable" }}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProviders>
          <MainStoreProvider>
            <header className="root_header sticky top-0 z-10 shadow inset-x-0">
              <div className="max-w-4xl mx-auto p-4">
                <h1 className="text-lg font-bold">GitHub 유저 검색 및 북마크</h1>
                <nav>
                  <ul className="flex space-x-4">
                    <li>
                      <Link href="/all-users">모든 유저</Link>
                    </li>
                    <li>
                      <Link href="/bookmarked">북마크된 유저</Link>
                    </li>
                  </ul>
                </nav>
              </div>
            </header>
            <main className="root_body max-w-4xl mx-auto p-4">
              {children}
              <FloatingActionButton />
            </main>
          </MainStoreProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
